CREATE DATABASE ART CHARACTER SET 'utf8';

USE ART;

CREATE TABLE AUTHOR (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    lastname VARCHAR(30),
    firstname VARCHAR(30),
    PRIMARY KEY (id)
);

CREATE TABLE ARTWORK (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    author_id SMALLINT UNSIGNED NOT NULL,
    translation_default_id SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE TRANSLATION (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    artwort_id SMALLINT UNSIGNED NOT NULL,
    lang VARCHAR(30) NOT NULL,
    translation TEXT NOT NULL,
    PRIMARY KEY (id)
);
